#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="${1:-skills}"
OUT="${ROOT_DIR}/docs-unified-skills.md"

{
  echo "# Unified Skills Index"
  echo
  find "$ROOT_DIR" -mindepth 2 -maxdepth 2 -name SKILL.md -print | sort | while read -r f; do
    name="$(awk 'BEGIN{in=0} /^---/{in=!in; next} in && $1=="name:"{print $2; exit}' "$f")"
    desc="$(awk 'BEGIN{in=0} /^---/{in=!in; next} in && $1=="description:"{$1=""; sub(/^ /,""); print; exit}' "$f")"
    if [[ -n "${name:-}" ]]; then
      echo "- \$$name — $desc"
    fi
  done
  echo
  echo "Generated by unify_skills.sh"
} > "$OUT"

echo "Wrote $OUT"
